### PR TITLE
Agressively re-focus on #reginput

### PR DESCRIPTION
**Pull request by thefinn93**
We were having some issues where the reginput box was getting defocused. This change just makes sure that doesn't happen. From everything I've seen so far this shouldn't break anything, but i'm not 100% sure and would like feedback.

### CODE REVIEW

**Comment by gohanman** [comment]
I'm not crazy about this. No one else has this problem in thousands of hours of usage every week. Brute forcing like this rather than trying to find the actual problem unique to your environment seems like a bad solution. 

Also, this will cause problems in most browsers if the defocus problem occurs while the cashier is trying to type. If you call `focus` while the element already has focus it doesn't do anything but if the element has lost focus re-focusing will move the cursor to the beginning. 

Does this perhaps relate to the 2nd window? That would at least narrow down more precisely where a refocus is needed, although there might be better ways to handle that window in general.

**Comment by danry25** [comment]
Pretty sure that this defocusing issue is caused in part by the customer display, and when focus is returned to the cashier window, Firefox seems to not focus on the text input box.

**Comment by gohanman** [comment]
I'd prefer having a solution in `CustomerDisplay.js` instead of this brute force approach. Making that 2nd display behave correctly is going to surely involving digging into the related javascript eventually. It's just a question or now or later.

**Comment by gohanman** [comment]
This seems more targeted: https://github.com/CORE-POS/IS4C/commit/435bf7eefe020cafa651261a7269c5d87c93583e

When interacting with the 2nd window:
* Get the currently focused element
* Do interaction with 2nd window
* Return focus to original element

**Comment by gohanman** [comment]
Did the suggested alternate solution work - i.e., can I close this?

**Comment by thefinn93** [comment]
We haven't fully tested the alternative but I agree that that path is a better one.

**Pull request closed without merging**
